version: '3.3'

services:

  web:
   image: nginx
   volumes:
     - ./site:/usr/share/nginx/html
   ports:
     - "8080:80"
   environment:
     - NGINX_HOST=192.168.23.123
     - NGINX_PORT=80

  database:
   image: redis
   ports:
     - "5555:55"
